const baseLight = {
  text: "#0D1B3E",
  background: "#F4F6FA",
  foreground: "#0D1B3E",
  card: "#FFFFFF",
  cardForeground: "#0D1B3E",
  primaryForeground: "#FFFFFF",
  secondary: "#E8EEF8",
  muted: "#E8EEF8",
  mutedForeground: "#6B7A99",
  accent: "#F59E0B",
  accentForeground: "#0D1B3E",
  destructive: "#DC2626",
  destructiveForeground: "#FFFFFF",
  border: "#D1D9ED",
  input: "#D1D9ED",
  success: "#16A34A",
  successForeground: "#FFFFFF",
  warning: "#D97706",
  warningForeground: "#FFFFFF",
};

const baseDark = {
  text: "#ECF0F6",
  background: "#0B0F19",
  foreground: "#ECF0F6",
  card: "#141C2F",
  cardForeground: "#ECF0F6",
  primaryForeground: "#FFFFFF",
  secondary: "#1E293B",
  muted: "#1E293B",
  mutedForeground: "#94A3B8",
  accent: "#F59E0B",
  accentForeground: "#0F172A",
  destructive: "#EF4444",
  destructiveForeground: "#FFFFFF",
  border: "#1E293B",
  input: "#1E293B",
  success: "#10B981",
  successForeground: "#FFFFFF",
  warning: "#F59E0B",
  warningForeground: "#FFFFFF",
};

const colors = {
  adminLight: {
    ...baseLight,
    tint: "#1E3A8A",
    primary: "#1E3A8A",
    secondaryForeground: "#1E3A8A",
  },
  adminDark: {
    ...baseDark,
    tint: "#3B82F6",
    primary: "#3B82F6",
    secondaryForeground: "#3B82F6",
  },
  teacherLight: {
    ...baseLight,
    tint: "#059669",
    primary: "#059669",
    secondaryForeground: "#059669",
  },
  teacherDark: {
    ...baseDark,
    tint: "#10B981",
    primary: "#10B981",
    secondaryForeground: "#10B981",
  },
  parentLight: {
    ...baseLight,
    tint: "#7C3AED",
    primary: "#7C3AED",
    secondaryForeground: "#7C3AED",
  },
  parentDark: {
    ...baseDark,
    tint: "#8B5CF6",
    primary: "#8B5CF6",
    secondaryForeground: "#8B5CF6",
  },
  defaultLight: {
    ...baseLight,
    tint: "#0F172A",
    primary: "#0F172A",
    secondaryForeground: "#0F172A",
  },
  defaultDark: {
    ...baseDark,
    tint: "#F8FAFC",
    primary: "#F8FAFC",
    secondaryForeground: "#F8FAFC",
    primaryForeground: "#0F172A",
  },
  radius: 12,
};

export default colors;
